# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffd0538a52584f01a212301cdf6303cf1d700e38628323761291300342174ae57e40fb92b093113e21701d20e2dcb6fef16652738be0a94fa2e21c22a0d9e765

test:
  secret_key_base: 48b821dd8f8dd7a29cbc1fb1ceb12062763e047eb8e90758efaa36fe35c01986aa0e4c50fbc6cf9d33ec28d4934c5f0814f3f9c553a3928e28ea5b70a670b1e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
